Repository youzan/vant, pull requests merged in 2023-09, with the labels that each got.

#12227 feat(auto-import-resolver): add auto-import-resolver package
  packages/auto-import-resolver/LICENSE
  packages/auto-import-resolver/README.md
  packages/auto-import-resolver/README.zh-CN.md
  packages/auto-import-resolver/build.js
  packages/auto-import-resolver/package.json
  packages/auto-import-resolver/src/index.ts
  packages/auto-import-resolver/tsconfig.json
  packages/auto-import-resolver/vant.config.mjs
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
  pnpm-lock.yaml
Labels: change: feat

#12239 docs: add Vite and Nuxt guide to quickstart
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: docs

#12241 docs(auto-import-resolver): update README and folder name
  packages/vant-auto-import-resolver/LICENSE
  packages/vant-auto-import-resolver/README.md
  packages/vant-auto-import-resolver/README.zh-CN.md
  packages/vant-auto-import-resolver/build.js
  packages/vant-auto-import-resolver/package.json
  packages/vant-auto-import-resolver/src/index.ts
  packages/vant-auto-import-resolver/tsconfig.json
  packages/vant-auto-import-resolver/vant.config.mjs
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
  pnpm-lock.yaml
Labels: change: docs

#12242 docs(auto-import-resolver): add Rspack usage
  packages/vant-auto-import-resolver/README.md
  packages/vant-auto-import-resolver/README.zh-CN.md
  packages/vant-auto-import-resolver/package.json
Labels: change: docs

#12243 fix(auto-import-resolver): type mismatch in TS projects
  packages/vant-auto-import-resolver/src/index.ts
Labels: change: fix

#12240 feat(ConfigProvider): add theme-vars-scope props enable root affects
  packages/vant/src/config-provider/ConfigProvider.tsx
  packages/vant/src/config-provider/README.md
  packages/vant/src/config-provider/README.zh-CN.md
  packages/vant/src/config-provider/index.ts
  packages/vant/src/config-provider/test/index.spec.tsx
Labels: change: feat

#12237 fix(eslint): eslint 不再支持.eslintignore文件, 需要在.eslintrc配置ignorePatterns
  packages/vant/.eslintignore
  packages/vant/.eslintrc
Labels: change: fix

#12246 docs(ConfigProvider): update the guide of modify CSS vars
  packages/vant/src/config-provider/README.md
  packages/vant/src/config-provider/README.zh-CN.md
Labels: change: docs

#12260 feat(Cell): add css vars to customize font size of the cell value
  packages/vant/src/cell/README.md
  packages/vant/src/cell/README.zh-CN.md
  packages/vant/src/cell/index.less
Labels: change: feat

#12264 feat(ConfigProvider): supplement the type declaration of ConfigProviderThemeVars
  packages/vant/src/config-provider/types.ts
Labels: change: feat

#12267 fix(ConfigProvider): ConfigProviderThemeVars `fontSizeXs` hump
  packages/vant/src/config-provider/types.ts
Labels: change: fix

#12258 feat(NavBar): add leftDisabled and rightDisabled prop
  packages/vant/src/nav-bar/NavBar.tsx
  packages/vant/src/nav-bar/README.md
  packages/vant/src/nav-bar/README.zh-CN.md
  packages/vant/src/nav-bar/index.less
Labels: change: feat

#12270 docs(NavBar): add disable button demo
  packages/vant/src/nav-bar/NavBar.tsx
  packages/vant/src/nav-bar/README.md
  packages/vant/src/nav-bar/README.zh-CN.md
  packages/vant/src/nav-bar/demo/index.vue
  packages/vant/src/nav-bar/index.less
  packages/vant/src/nav-bar/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/nav-bar/test/__snapshots__/demo.spec.ts.snap
Labels: change: docs

#12273 docs(changelog): vant@4.6.8
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12274 feat(Calendar): add click-disabled-date event
  packages/vant/src/calendar/Calendar.tsx
  packages/vant/src/calendar/CalendarDay.tsx
  packages/vant/src/calendar/CalendarMonth.tsx
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
  packages/vant/src/calendar/test/index.spec.ts
Labels: change: feat

#12275 docs(Picker): 补充 picker 组件的文档
  packages/vant/src/picker/README.md
  packages/vant/src/picker/README.zh-CN.md
Labels: change: docs

#12280 feat(Uploader): add `--van-uploader-border-radius` css variables
  packages/vant/src/uploader/README.md
  packages/vant/src/uploader/README.zh-CN.md
  packages/vant/src/uploader/index.less
Labels: change: feat

#12289 docs(Uploader): add FAQ about camera permission
  packages/vant/src/uploader/README.md
  packages/vant/src/uploader/README.zh-CN.md
Labels: change: docs

#12291 feat(Icon): add 11 new icons
  packages/vant-icons/assets/icons.sketch
  packages/vant-icons/contribution.zh-CN.md
  packages/vant-icons/src/common.less
  packages/vant-icons/src/config.js
  packages/vant-icons/src/encode-woff2.less
  packages/vant-icons/src/index.less
Labels: change: feat

#12309 feat(SwipeCell): Fix triggered close by clickAway when in running beforeClose
  packages/vant/src/swipe-cell/README.md
  packages/vant/src/swipe-cell/README.zh-CN.md
  packages/vant/src/swipe-cell/SwipeCell.tsx
  packages/vant/src/swipe-cell/demo/index.vue
  packages/vant/src/swipe-cell/test/index.spec.js
  packages/vant/src/utils/interceptor.ts
  packages/vant/src/utils/test/interceptor.spec.ts
Labels: change: feat

#12300 fix(Picker): fix bug the content of the popup window is not consistent with the Chinese version under the English version
  packages/vant/src/picker/demo/index.vue
Labels: change: fix

#12310 feat(AddressEdit): add change event for name and tel input
  packages/vant/src/address-edit/AddressEdit.tsx
  packages/vant/src/address-edit/README.md
  packages/vant/src/address-edit/README.zh-CN.md
  packages/vant/src/address-edit/test/index.spec.ts
Labels: change: feat

#12304 fix(Signature): fix checking if canvas is empty when backgoundColor is set
  packages/vant/src/signature/Signature.tsx
Labels: change: fix

#12314 fix(FloatingPanel): dragging down causes the page to move
  packages/vant/src/floating-panel/FloatingPanel.tsx
  packages/vant/src/floating-panel/README.md
  packages/vant/src/floating-panel/README.zh-CN.md
Labels: change: fix

#12316 types(Dialog): improve showDialog return type
  packages/vant/src/dialog/function-call.tsx
  packages/vant/src/swipe-cell/README.md
  packages/vant/src/swipe-cell/README.zh-CN.md
  packages/vant/src/swipe-cell/demo/index.vue
Labels: change: feat

#12318 docs(changelog): vant 4.7.0
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
  packages/vant/src/address-edit/README.md
  packages/vant/src/address-edit/README.zh-CN.md
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
Labels: change: docs

#12317 feat(FloatingPanel): optimize bounce animate
  packages/vant/src/floating-panel/FloatingPanel.tsx
  packages/vant/src/floating-panel/index.less
  packages/vant/src/floating-panel/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/floating-panel/test/__snapshots__/index.spec.tsx.snap
Labels: change: feat

#12327 fix(Popup): fix failed to inherit scopedId
  packages/vant/src/composables/use-scope-id.ts
  packages/vant/src/popup/Popup.tsx
Labels: change: fix

#12328 fix(CellGroup): failed to inherit scopeId with title
  packages/vant/src/cell-group/CellGroup.tsx
Labels: change: fix

#12331 fix(docs): mistypo Georqia to Georgia
  packages/vant/src/form/README.md
  packages/vant/src/tree-select/README.md
  packages/vant/src/tree-select/demo/data-en.ts
  packages/vant/src/tree-select/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/tree-select/test/__snapshots__/demo.spec.ts.snap
Labels: change: fix
