Repository youzan/vant, pull requests merged in 2023-11, with the labels that each got.

#12425 fix(canendar): subtitle supports reactive
  packages/vant/src/calendar/Calendar.tsx
Labels: change: fix

#12426 feat(ImagePreview): expose resetScale method
  packages/vant/src/image-preview/ImagePreview.tsx
  packages/vant/src/image-preview/ImagePreviewItem.tsx
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
  packages/vant/src/image-preview/test/index.spec.ts
  packages/vant/src/image-preview/types.ts
Labels: change: feat

#12429 docs(field): update props size
  packages/vant/src/field/README.md
  packages/vant/src/field/README.zh-CN.md
Labels: change: docs

#12427 docs(cell): update props size
  packages/vant/src/cell/README.md
  packages/vant/src/cell/README.zh-CN.md
Labels: change: docs

#12434 feat(Highlight): add highlight component
  packages/vant/src/config-provider/types.ts
  packages/vant/src/highlight/Highlight.tsx
  packages/vant/src/highlight/README.md
  packages/vant/src/highlight/README.zh-CN.md
  packages/vant/src/highlight/demo/index.vue
  packages/vant/src/highlight/index.less
  packages/vant/src/highlight/index.ts
  packages/vant/src/highlight/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/highlight/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/highlight/test/demo-ssr.spec.ts
  packages/vant/src/highlight/test/demo.spec.ts
  packages/vant/src/highlight/test/index.spec.ts
  packages/vant/src/highlight/types.ts
  packages/vant/vant.config.mjs
Labels: change: feat

#12436 feat(Checker): add checked and disabled params to the default slot
  packages/vant/src/checkbox/Checker.tsx
  packages/vant/src/checkbox/README.md
  packages/vant/src/checkbox/README.zh-CN.md
  packages/vant/src/checkbox/test/index.spec.ts
  packages/vant/src/radio/README.md
  packages/vant/src/radio/README.zh-CN.md
Labels: change: feat

#12438 docs(Highlight): add version tip
  packages/vant/src/highlight/README.md
  packages/vant/src/highlight/README.zh-CN.md
  packages/vant/src/highlight/demo/index.vue
Labels: change: docs

#12439 feat(Row): gutter support vertical space
  packages/vant/src/col/Col.tsx
  packages/vant/src/col/README.md
  packages/vant/src/col/README.zh-CN.md
  packages/vant/src/col/demo/index.vue
  packages/vant/src/col/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/col/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/col/test/index.spec.tsx
  packages/vant/src/row/Row.tsx
Labels: change: feat

#12454 docs(Overlay): add set z-index demo
  packages/vant/src/overlay/README.md
  packages/vant/src/overlay/README.zh-CN.md
  packages/vant/src/overlay/demo/index.vue
  packages/vant/src/overlay/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/overlay/test/__snapshots__/demo.spec.ts.snap
Labels: change: docs

#12455 docs: add Rsbuild to quickstart
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: docs

#12460 docs(collapse): fix missing `ref` tags
  packages/vant/src/collapse/README.md
  packages/vant/src/collapse/README.zh-CN.md
Labels: change: docs

#12464 docs(collapse): fix translation Error
  packages/vant/src/collapse/README.md
  packages/vant/src/collapse/demo/index.vue
  packages/vant/src/collapse/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/collapse/test/__snapshots__/demo.spec.ts.snap
Labels: change: docs

#12465 docs(dialog): fix translation Error and keep the sample code the same
  packages/vant/src/dialog/README.md
  packages/vant/src/dialog/README.zh-CN.md
  packages/vant/src/dialog/demo/index.vue
Labels: change: docs

#12471 perf(TextEllipsis): reuse windowWidth to avoid repeat calculations
  packages/vant/src/text-ellipsis/TextEllipsis.tsx
Labels: change: feat

#12469 docs(TreeSelect): correct variable names
  packages/vant/src/tree-select/README.md
  packages/vant/src/tree-select/README.zh-CN.md
Labels: change: docs

#12472 feat(TextEllipsis): add the toggle instance method
  packages/vant/src/text-ellipsis/README.md
  packages/vant/src/text-ellipsis/README.zh-CN.md
  packages/vant/src/text-ellipsis/TextEllipsis.tsx
  packages/vant/src/text-ellipsis/index.ts
  packages/vant/src/text-ellipsis/types.ts
Labels: change: feat

#12475 docs: add Rsbuild scaffold guide
  README.md
  README.zh-CN.md
  packages/vant/docs/markdown/home.en-US.md
  packages/vant/docs/markdown/home.zh-CN.md
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: docs
