Repository youzan/vant, pull requests merged in 2023-08, with the labels that each got.

#12145 feat(Locale): add Serbian language to internationalization
  packages/vant/src/locale/lang/sr-SR.ts
Labels: change: feat

#12152 docs(Radio): add document description for the css var '--van-radio-dot-size'
  packages/vant/src/radio/README.md
  packages/vant/src/radio/README.zh-CN.md
Labels: change: docs

#12153 feat(ImagePreview): add closeOnClickOverlay option
  packages/vant/src/image-preview/ImagePreview.tsx
  packages/vant/src/image-preview/ImagePreviewItem.tsx
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
  packages/vant/src/image-preview/function-call.tsx
  packages/vant/src/image-preview/test/index.spec.ts
  packages/vant/src/image-preview/types.ts
Labels: change: feat

#12154 feat(List): add scroller prop
  packages/vant/src/list/List.tsx
  packages/vant/src/list/README.md
  packages/vant/src/list/README.zh-CN.md
Labels: change: feat

#12157 feat(FloatingPanel): add lock-scroll prop
  packages/vant/src/floating-panel/FloatingPanel.tsx
  packages/vant/src/floating-panel/README.md
  packages/vant/src/floating-panel/README.zh-CN.md
Labels: change: feat

#12166 types(Toast): add `ToastWrapperInstance` export.
  packages/vant/src/toast/README.md
  packages/vant/src/toast/README.zh-CN.md
  packages/vant/src/toast/index.ts
Labels: change: feat

#12161 fix(floatingPanel): Lag caused by scrollbar and panel movement #12146
  packages/vant/src/floating-panel/FloatingPanel.tsx
Labels: change: fix

#12182 docs: add instructions for bun package manager
  README.md
  README.zh-CN.md
  packages/create-vant-cli-app/generators/vue2/docs/quickstart.md
  packages/create-vant-cli-app/generators/vue3/docs/quickstart.md
  packages/vant-area-data/README.md
  packages/vant-cli/README.md
  packages/vant-cli/README.zh-CN.md
  packages/vant-cli/docs/config.md
  packages/vant-cli/docs/config.zh-CN.md
  packages/vant-compat/README.md
  packages/vant-eslint-config/README.md
  packages/vant-icons/README.md
  packages/vant-popperjs/README.md
  packages/vant-touch-emulator/README.md
  packages/vant-use/README.md
  packages/vant/docs/markdown/migrate-from-v3.en-US.md
  packages/vant/docs/markdown/migrate-from-v3.zh-CN.md
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
  packages/vant/docs/markdown/vant-use-intro.en-US.md
  packages/vant/docs/markdown/vant-use-intro.zh-CN.md
  packages/vant/src/area/README.md
  packages/vant/src/area/README.zh-CN.md
  packages/vant/src/cascader/README.zh-CN.md
Labels: change: docs

#12188 fix(cli): should escape curly brackets in markdown
  packages/vant-cli/src/compiler/vite-plugin-md.ts
Labels: change: fix

#12189 fix(Dialog): improve slot exit judgment
  packages/vant/src/dialog/Dialog.tsx
Labels: change: fix

#12199 docs(changelog): vant@4.6.5
  packages/vant/docs/formatChangelog.mjs
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12207 fix(FloatingBubble): does not update state while hidden
  packages/vant/src/floating-bubble/FloatingBubble.tsx
Labels: change: fix

#12208 feat(DropdownItem): supports boolean Value
  packages/vant/src/dropdown-item/DropdownItem.tsx
  packages/vant/src/dropdown-item/types.ts
  packages/vant/src/dropdown-menu/README.md
  packages/vant/src/dropdown-menu/README.zh-CN.md
Labels: change: feat

#12209 docs(changelog): vant@4.6.6
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12211 feat(vant-use): add useRaf
  packages/vant-use/src/index.ts
  packages/vant-use/src/useRaf/index.ts
  packages/vant/docs/markdown/use-raf.en-US.md
  packages/vant/docs/markdown/use-raf.zh-CN.md
  packages/vant/docs/markdown/vant-use-intro.en-US.md
  packages/vant/docs/markdown/vant-use-intro.zh-CN.md
  packages/vant/vant.config.mjs
Labels: change: feat

#12223 docs: improve the menu position of back-top
  packages/vant/vant.config.mjs
Labels: change: docs

#12216 feat(Checkbox): add indeterminate status
  packages/vant/src/checkbox/Checkbox.tsx
  packages/vant/src/checkbox/Checker.tsx
  packages/vant/src/checkbox/README.md
  packages/vant/src/checkbox/README.zh-CN.md
  packages/vant/src/checkbox/demo/index.vue
  packages/vant/src/checkbox/index.less
  packages/vant/src/checkbox/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/checkbox/test/__snapshots__/demo.spec.ts.snap
Labels: change: feat
