Repository youzan/vant, pull requests merged in 2023-12, with the labels that each got.

#12483 fix(TextEllipsis): fix missing param for toggle
  packages/vant/src/text-ellipsis/types.ts
Labels: change: fix

#12491 docs(image-preview): usage of Supplementing `className`
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
Labels: change: docs

#12500 docs(Quickstart): unplugin-vue-components usage updated (#12499)
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: docs

#12512 docs(changelog): vant@4.8.1
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12516 fix(ci): eslint on windows (#12492)
  package.json
  packages/create-vant-cli-app/generators/vue2/src/demo-button/index.vue
  packages/create-vant-cli-app/generators/vue3/src/demo-button/index.vue
Labels: change: fix

#12521 fix(ImagePreview): double-scale and close-on-click-overlay may not work in certain scenarios
  packages/vant/src/image-preview/ImagePreviewItem.tsx
  packages/vant/src/image-preview/test/index.spec.ts
  packages/vant/src/image-preview/test/shared.ts
Labels: change: fix

#12251 feat(DropdownMenu): add auto-locate prop
  packages/vant/src/dropdown-item/DropdownItem.tsx
  packages/vant/src/dropdown-menu/DropdownMenu.tsx
  packages/vant/src/dropdown-menu/README.md
  packages/vant/src/dropdown-menu/README.zh-CN.md
  packages/vant/src/dropdown-menu/test/index.spec.tsx
  packages/vant/src/utils/dom.ts
  packages/vant/src/utils/test/index.spec.ts
Labels: change: feat

#12541 perf(CLI): improve markdown compile performance
  packages/vant-cli/cjs/md-loader.cjs
  packages/vant-cli/src/compiler/compile-site.ts
Labels: change: perf
