Repository youzan/vant, pull requests merged in 2023-10, with the labels that each got.

#12334 feat(cli): using rslog
  .npmrc
  packages/create-vant-cli-app/package.json
  packages/create-vant-cli-app/src/generator.ts
  packages/create-vant-cli-app/src/index.ts
  packages/vant-cli/package.json
  packages/vant-cli/src/commands/build.ts
  packages/vant-cli/src/commands/commit-lint.ts
  packages/vant-cli/src/commands/lint.ts
  packages/vant-cli/src/commands/release.ts
  packages/vant-cli/src/common/logger.ts
  packages/vant-cli/src/common/manager.ts
  packages/vant-cli/src/compiler/compile-site.ts
  packages/vant-cli/src/compiler/compile-style.ts
  packages/vant-cli/src/index.ts
  pnpm-lock.yaml
Labels: change: feat

#12338 docs: add more ecosystem projects
  README.md
  README.zh-CN.md
  packages/vant/docs/markdown/home.en-US.md
  packages/vant/docs/markdown/home.zh-CN.md
Labels: change: docs

#12342 feat(Notify): add jsdoc for utility functions
  packages/vant/src/notify/README.md
  packages/vant/src/notify/README.zh-CN.md
  packages/vant/src/notify/function-call.tsx
Labels: change: feat

#12343 feat(Dialog): add JSDoc for utility functions
  packages/vant/src/dialog/README.md
  packages/vant/src/dialog/README.zh-CN.md
  packages/vant/src/dialog/function-call.tsx
Labels: change: feat

#12344 feat(Toast): add JSDoc for utility functions
  packages/vant/src/toast/README.md
  packages/vant/src/toast/README.zh-CN.md
  packages/vant/src/toast/function-call.tsx
Labels: change: feat

#12345 docs(ImagePreview): improve English document
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
  packages/vant/src/image-preview/function-call.tsx
Labels: change: docs

#12346 docs(changelog): vant@4.7.1
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12354 feat(Icon): add font-family css var
  packages/vant-icons/src/common.less
Labels: change: feat

#12356 fix(Icons): compatible with the browser range of Vant 2
  packages/vant-icons/src/common.less
Labels: change: fix

#12359 fix(Uploader): multiple reupload only choose one & cancel chose problem
  packages/vant/src/uploader/Uploader.tsx
Labels: change: fix

#12360 feat: add enableDoubleScale attribute
  packages/vant/src/image-preview/ImagePreview.tsx
  packages/vant/src/image-preview/ImagePreviewItem.tsx
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
  packages/vant/src/image-preview/function-call.tsx
  packages/vant/src/image-preview/types.ts
  pnpm-lock.yaml
Labels: change: feat

#12367 docs(changelog): vant@4.7.2
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12371 fix(ConfigProvider): export missing theme vars
  packages/vant/src/config-provider/types.ts
Labels: change: fix

#12381 feat(locale): Add Arabic Locale
  packages/vant/src/locale/README.md
  packages/vant/src/locale/README.zh-CN.md
  packages/vant/src/locale/lang/ar-SA.ts
Labels: change: feat

#12382 docs(auto-import-resolver): add doc for importStyle option
  packages/vant-auto-import-resolver/README.md
  packages/vant-auto-import-resolver/README.zh-CN.md
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: docs

#12383 feat(auto-import-resolver): add module option
  packages/vant-auto-import-resolver/README.md
  packages/vant-auto-import-resolver/README.zh-CN.md
  packages/vant-auto-import-resolver/src/index.ts
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: feat

#12395 docs(Tab): keep docs and example the same
  packages/vant/src/tab/README.md
  packages/vant/src/tab/README.zh-CN.md
Labels: change: docs

#12396 style: replace word-break with overflow-wrap
  packages/vant/src/field/index.less
  packages/vant/src/text-ellipsis/index.less
Labels: change: feat

#12393 fix(AddressEdit): area field validate error when showArea is false
  packages/vant/src/address-edit/AddressEdit.tsx
Labels: change: fix

#12397 fix(@vant/area-data): add exports types
  packages/vant-area-data/package.json
Labels: change: fix

#12394 feat(Tab): add showTitle prop for Tab
  packages/vant/src/back-top/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/empty/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/floating-panel/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/icon/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/index-bar/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/list/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/picker-group/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/pull-refresh/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/tab/README.md
  packages/vant/src/tab/README.zh-CN.md
  packages/vant/src/tab/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/tab/test/index.spec.tsx
  packages/vant/src/tabs/Tabs.tsx
Labels: change: feat

#12385 fix(Search): fix search style when has error message
  packages/vant/src/search/Search.tsx
  packages/vant/src/search/index.less
Labels: change: fix

#12408 docs(Tabs): add show-header prop
  packages/vant/src/back-top/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/empty/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/floating-panel/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/icon/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/index-bar/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/list/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/picker-group/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/pull-refresh/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/tab/README.md
  packages/vant/src/tab/README.zh-CN.md
  packages/vant/src/tab/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/tab/test/index.spec.tsx
  packages/vant/src/tabs/Tabs.tsx
Labels: change: docs

#12402 fix(PickerGroup): only filter Comment vnode
  packages/vant/src/picker-group/PickerGroup.tsx
  packages/vant/src/picker-group/demo/SelectDateTime.vue
Labels: change: fix

#12405 feat(Signature): expose resize method
  packages/vant/src/signature/Signature.tsx
  packages/vant/src/signature/index.ts
  packages/vant/src/signature/test/index.spec.ts
  packages/vant/src/signature/types.ts
Labels: change: feat

#12411 docs(Signature): add resize method
  packages/vant/src/signature/README.md
  packages/vant/src/signature/README.zh-CN.md
  packages/vant/src/space/README.zh-CN.md
Labels: change: docs

#12412 docs(progress): remove outdated resize method
  packages/vant/src/progress/README.md
  packages/vant/src/progress/README.zh-CN.md
  packages/vant/src/progress/types.ts
Labels: change: docs

#12413 docs(changelog): vant v4.7.3
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs
