Repository youzan/vant, pull requests merged in 2024-03, with the labels that each got.

#12660 feat(ImagePreview): add vertical prop
  packages/vant/src/image-preview/ImagePreview.tsx
  packages/vant/src/image-preview/types.ts
Labels: change: feat

#12663 docs(ImagePreview): add vertical prop
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
  packages/vant/src/image-preview/function-call.tsx
Labels: change: docs

#12666 fix(ImagePreview): allow user to swipe to next image when the current image is moved to the edge
  packages/vant/src/image-preview/ImagePreview.tsx
  packages/vant/src/image-preview/ImagePreviewItem.tsx
Labels: change: fix

#12654 feat(signature): export clear and submit method
  packages/vant/src/signature/README.md
  packages/vant/src/signature/README.zh-CN.md
  packages/vant/src/signature/Signature.tsx
  packages/vant/src/signature/types.ts
Labels: change: feat

#12693 docs: change tab's 'Before Change' into a real async function
  packages/vant/src/tab/README.md
  packages/vant/src/tab/README.zh-CN.md
  packages/vant/src/tab/demo/index.vue
Labels: change: docs

#12679 feat: support unplugin-auto-import plugin
  packages/vant-auto-import-resolver/README.md
  packages/vant-auto-import-resolver/README.zh-CN.md
  packages/vant-auto-import-resolver/src/index.ts
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: feat

#12671 feat(ActionSheet): add icon support to the actions data
  packages/vant/src/action-sheet/ActionSheet.tsx
  packages/vant/src/action-sheet/README.md
  packages/vant/src/action-sheet/README.zh-CN.md
  packages/vant/src/action-sheet/demo/index.vue
  packages/vant/src/action-sheet/index.less
  packages/vant/src/action-sheet/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/action-sheet/test/__snapshots__/demo.spec.ts.snap
Labels: change: feat

#12701 fix(ActionSheet): icon class name
  packages/vant/src/action-sheet/index.less
Labels: change: fix

#12703 docs(changelog): vant@4.8.6
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12707 docs(changelog): vant@4.8.7
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12708 docs(button): Keep Chinese and English documents consistent
  packages/vant/src/button/README.zh-CN.md
Labels: change: docs

#12721 docs(cell): correct the type of label
  packages/vant/src/cell/README.md
  packages/vant/src/cell/README.zh-CN.md
Labels: change: docs

#12730 fix(floating-bubble): update offset when the value changed
  packages/vant/src/floating-bubble/FloatingBubble.tsx
Labels: change: fix

#12734 fix(vant-cli): support defineOptions named
  packages/vant-cli/src/common/index.ts
Labels: change: fix

#12732 fix(PickerGroup): rendering correctly when using v-for
  packages/vant/src/picker-group/PickerGroup.tsx
  packages/vant/src/picker-group/test/index.spec.tsx
  packages/vant/src/utils/basic.ts
Labels: change: fix

#12740 feat(image-preview): export onLoad and style for image slot
  packages/vant/src/image-preview/ImagePreviewItem.tsx
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
  packages/vant/src/image-preview/test/index.spec.ts
Labels: change: feat

#12741 fix(TextEllipsis): should recalculate the ellipsis state when the component is activated
  packages/vant/src/text-ellipsis/TextEllipsis.tsx
  packages/vant/src/text-ellipsis/test/__snapshots__/index.spec.tsx.snap
  packages/vant/src/text-ellipsis/test/index.spec.tsx
Labels: change: fix

#12748 feat(AddressList): add event param for click-item
  packages/vant/src/address-list/AddressList.tsx
  packages/vant/src/address-list/AddressListItem.tsx
  packages/vant/src/address-list/README.md
  packages/vant/src/address-list/README.zh-CN.md
  packages/vant/src/address-list/test/index.spec.ts
Labels: change: feat

#12751 docs(ImagePreview): add image slot scale guide
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
Labels: change: docs

#12755 docs(changelog): vant v4.8.8
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs
