Repository youzan/vant, pull requests merged in 2024-04, with the labels that each got.

#12761 feat(TimePicker): support confirm and getSelectedTime methods
  packages/vant/src/time-picker/README.md
  packages/vant/src/time-picker/README.zh-CN.md
  packages/vant/src/time-picker/TimePicker.tsx
  packages/vant/src/time-picker/index.ts
Labels: change: feat

#12762 feat(DatePicker): support "confirm" method, support "getSelectedDate"…
  packages/vant/src/date-picker/DatePicker.tsx
  packages/vant/src/date-picker/README.md
  packages/vant/src/date-picker/README.zh-CN.md
  packages/vant/src/date-picker/index.ts
Labels: change: feat

#12744 feat(Coupon): support for checkbox usage
  packages/vant/docs/site/use-translate.ts
  packages/vant/src/coupon-cell/CouponCell.tsx
  packages/vant/src/coupon-list/CouponList.tsx
  packages/vant/src/coupon-list/README.md
  packages/vant/src/coupon-list/README.zh-CN.md
  packages/vant/src/coupon-list/demo/index.vue
  packages/vant/src/coupon-list/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/coupon-list/test/__snapshots__/demo.spec.ts.snap
Labels: change: feat

#12785 feat(DropdownMenu): add disabled for option
  packages/vant/src/dropdown-item/DropdownItem.tsx
  packages/vant/src/dropdown-item/index.less
  packages/vant/src/dropdown-item/types.ts
  packages/vant/src/dropdown-menu/README.md
  packages/vant/src/dropdown-menu/README.zh-CN.md
  packages/vant/src/dropdown-menu/index.less
  packages/vant/src/dropdown-menu/test/index.spec.tsx
  packages/vant/src/dropdown-menu/types.ts
Labels: change: feat

#12778 docs(list): update Error loading module code
  packages/vant/src/list/README.md
  packages/vant/src/list/README.zh-CN.md
Labels: change: docs

#12787 fix: warning `is not a valid value for v-model` in JetBrains IDE
  packages/vant-cli/src/compiler/web-types/formatter.ts
  packages/vant-cli/src/compiler/web-types/index.ts
  packages/vant-cli/src/compiler/web-types/parser.ts
Labels: change: fix

#12791 docs(changelog): @vant/cli 7.0.0
  packages/vant-cli/changelog.md
  packages/vant-cli/package.json
Labels: change: docs

#12792 fix(Cli): remove site tsconfig
  packages/vant-cli/site/tsconfig.json
Labels: change: fix

#12793 docs(changelog): vant v4.8.11
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12799 fix(cli): Vue SFC style binding failure
  packages/vant-cli/src/compiler/compile-sfc.ts
Labels: change: fix

#12809 feat(CLI): support for configuring Rsbuild
  packages/vant-cli/docs/config.md
  packages/vant-cli/docs/config.zh-CN.md
  packages/vant-cli/src/compiler/compile-site.ts
Labels: change: feat

#12818 fix(ImagePreview): swipeItem may be undefined
  packages/vant/src/image-preview/ImagePreviewItem.tsx
Labels: change: fix

#12839 feat(PickerGroup): add new prop showToolbar
  packages/vant/src/picker-group/PickerGroup.tsx
  packages/vant/src/picker-group/README.md
  packages/vant/src/picker-group/README.zh-CN.md
Labels: change: feat
