Repository youzan/vant, pull requests merged in 2024-05, with the labels that each got.

#12837 fix(IndexBar): render active anchor correctly when passing sticky & stickyOffsetTop
  packages/vant/src/index-bar/IndexBar.tsx
  packages/vant/src/index-bar/test/__snapshots__/index.spec.jsx.snap
  packages/vant/src/index-bar/test/index.spec.jsx
  packages/vant/test/dom.ts
Labels: change: fix

#12836 feat(Calendar): add switch-mode prop
  packages/vant/src/calendar/Calendar.tsx
  packages/vant/src/calendar/CalendarHeader.tsx
  packages/vant/src/calendar/CalendarMonth.tsx
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
  packages/vant/src/calendar/demo/SwicthModeField.vue
  packages/vant/src/calendar/demo/TiledDisplay.vue
  packages/vant/src/calendar/demo/index.vue
  packages/vant/src/calendar/index.less
  packages/vant/src/calendar/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/calendar/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/calendar/test/switch-mode.spec.ts
  packages/vant/src/calendar/types.ts
  packages/vant/src/calendar/utils.ts
Labels: change: feat

#12845 docs: remove all Gitee links
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy-v4-site.yml
  .github/workflows/sync-gitee.yml
  README.md
  README.zh-CN.md
  packages/vant/docs/markdown/contribution.en-US.md
  packages/vant/docs/markdown/contribution.zh-CN.md
  packages/vant/docs/markdown/home.en-US.md
  packages/vant/docs/markdown/home.zh-CN.md
  packages/vant/vant.config.mjs
Labels: change: docs

#12847 docs: remove gzip size badge
  README.md
  README.zh-CN.md
Labels: change: docs

#12848 docs: fix Rsbuild HTML build failed
  package.json
  packages/vant-cli/package.json
  pnpm-lock.yaml
Labels: change: docs

#12849 docs(changelog): vant@4.9.0
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
Labels: change: docs

#12860 fix(cli): CSS preprocessor for scoped
  packages/vant-cli/src/compiler/compile-sfc.ts
Labels: change: fix

#12861 feat: supports `imports` option for auto-import
  packages/vant-auto-import-resolver/README.md
  packages/vant-auto-import-resolver/README.zh-CN.md
  packages/vant-auto-import-resolver/src/index.ts
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: feat

#12857 fix(area): columns-placeholder prop rendering error
  packages/vant/src/area/README.md
  packages/vant/src/area/README.zh-CN.md
  packages/vant/src/area/demo/index.vue
  packages/vant/src/area/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/area/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/area/test/index.spec.ts
  packages/vant/src/area/utils.ts
Labels: change: fix

#12876 fix: VantImports type error
  packages/vant-auto-import-resolver/src/index.ts
Labels: change: fix

#12885 fix(Tab): incorrect style
  packages/vant/src/tabs/index.less
Labels: change: fix
