Repository youzan/vant, pull requests merged in 2024-02, with the labels that each got.

#12606 docs: improve quickstart tips
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: docs

#12614 fix(DropdownMenu): fix recursive update when passing object literal to title-class
  packages/vant/src/dropdown-menu/DropdownMenu.tsx
  packages/vant/src/dropdown-menu/test/index.spec.tsx
Labels: change: fix

#12616 docs(changelog): vant@4.8.4
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12619 docs: update docs for params related to Picker events
  packages/vant/src/date-picker/README.md
  packages/vant/src/date-picker/README.zh-CN.md
  packages/vant/src/time-picker/README.md
  packages/vant/src/time-picker/README.zh-CN.md
  packages/vant/src/time-picker/test/index.spec.tsx
Labels: change: docs

#12620 docs(DatePicker): fix en-docs error
  packages/vant/src/date-picker/README.md
Labels: change: docs

#12624 fix(NumberKeyboard): render delete slot correctly when theme is custom
  packages/vant/src/number-keyboard/NumberKeyboard.tsx
  packages/vant/src/number-keyboard/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/number-keyboard/test/index.spec.ts
Labels: change: fix

#12627 docs(Uploader): fix miss double quote
  packages/vant/src/uploader/README.zh-CN.md
Labels: change: docs

#12628 docs: add full registration guide
  packages/vant/docs/markdown/advanced-usage.en-US.md
  packages/vant/docs/markdown/advanced-usage.zh-CN.md
Labels: change: docs

#12629 docs: add Rsbuild import on demand guide
  packages/vant/docs/markdown/quickstart.en-US.md
  packages/vant/docs/markdown/quickstart.zh-CN.md
Labels: change: docs

#12641 feat(Image): add `crossorigin` & `referrerpolicy`
  packages/vant/src/image/Image.tsx
  packages/vant/src/image/README.md
  packages/vant/src/image/README.zh-CN.md
  packages/vant/src/image/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/image/test/index.spec.ts
Labels: change: feat

#12645 docs(changelog): vant@4.8.5
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs
