Repository youzan/vant, pull requests merged in 2024-07, with the labels that each got.

#12985 types(Notify): add missing teleport type
  packages/vant/src/notify/types.ts
Labels: change: feat

#13000 docs: mark legacy versions as EOL
  packages/vant/docs/markdown/home.en-US.md
  packages/vant/docs/markdown/home.zh-CN.md
  packages/vant/docs/markdown/release-note-v4.en-US.md
  packages/vant/docs/markdown/release-note-v4.zh-CN.md
Labels: change: docs

#13003 docs: add changelog notices
  .github/workflows/release-tag.yml
  packages/vant/docs/formatChangelog.mjs
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#13006 fix(Calendar): disable the previous month button correctly when the minDate is the current time
  packages/vant/src/calendar/CalendarHeader.tsx
  packages/vant/src/calendar/test/switch-mode.spec.ts
Labels: change: fix

#13005 fix(TextEllipsis): calculate the width of the action slot correctly
  packages/vant/src/text-ellipsis/TextEllipsis.tsx
  packages/vant/src/text-ellipsis/test/__snapshots__/demo-ssr.spec.ts.snap
Labels: change: fix

#13008 fix(Calendar): correctly change the panelDate when the selected date is the last day of each month
  packages/vant/src/calendar/CalendarHeader.tsx
  packages/vant/src/calendar/test/switch-mode.spec.ts
  packages/vant/src/calendar/utils.ts
Labels: change: fix

#13012 feat(Uploader): expose reuploadFile method
  packages/vant/src/uploader/README.md
  packages/vant/src/uploader/README.zh-CN.md
  packages/vant/src/uploader/Uploader.tsx
  packages/vant/src/uploader/test/index.spec.ts
  packages/vant/src/uploader/types.ts
Labels: change: feat

#13039 feat(SwipeCell): add event param for before-close
  packages/vant/src/swipe-cell/README.md
  packages/vant/src/swipe-cell/README.zh-CN.md
  packages/vant/src/swipe-cell/SwipeCell.tsx
  packages/vant/src/swipe-cell/test/index.spec.js
Labels: change: feat
