Repository youzan/vant, pull requests merged in 2024-06, with the labels that each got.

#12902 docs: add new document site URL
  README.md
  README.zh-CN.md
  packages/vant-cli/docs/config.md
  packages/vant-cli/docs/config.zh-CN.md
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
  packages/vant/docs/markdown/home.zh-CN.md
  packages/vant/docs/markdown/release-note-v4.en-US.md
  packages/vant/docs/markdown/release-note-v4.zh-CN.md
  packages/vant/vant.config.mjs
Labels: change: docs

#12897 feat(floating-panel): support header slot
  packages/vant/src/floating-panel/FloatingPanel.tsx
  packages/vant/src/floating-panel/README.md
  packages/vant/src/floating-panel/README.zh-CN.md
  packages/vant/src/floating-panel/test/__snapshots__/index.spec.tsx.snap
  packages/vant/src/floating-panel/test/index.spec.tsx
Labels: change: feat

#12887 feat(AddressList): support multiple selection
  packages/vant/src/address-list/AddressList.tsx
  packages/vant/src/address-list/AddressListItem.tsx
  packages/vant/src/address-list/README.md
  packages/vant/src/address-list/README.zh-CN.md
  packages/vant/src/address-list/test/index.spec.ts
Labels: change: feat

#12903 feat(cli): bump Rsbuild v0.7
  packages/vant-cli/package.json
  packages/vant-cli/src/compiler/compile-site.ts
  pnpm-lock.yaml
Labels: change: feat

#12904 docs(changelog): vant@4.9.1
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12917 fix(Card): render correctly when the price is an integer
  packages/vant/src/card/Card.tsx
  packages/vant/src/card/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/card/test/index.spec.ts
  packages/vant/src/swipe-cell/test/__snapshots__/demo-ssr.spec.ts.snap
Labels: change: fix

#12910 fix(Notify): add zIndex type
  packages/vant/src/notify/types.ts
Labels: change: fix

#12919 docs(Notify): fix z-index option case
  packages/vant/src/notify/README.md
  packages/vant/src/notify/README.zh-CN.md
Labels: change: docs

#12918 fix(Tab): "scrollLeftTo" function could not handle decimal correctly
  packages/vant/src/tabs/utils.ts
Labels: change: fix

#12920 docs(nav-bar): replace click-right with click-left for second example
  packages/vant/src/nav-bar/demo/index.vue
Labels: change: docs

#12935 docs(Tab): refine the description of 'props'
  packages/vant/src/tab/README.md
  packages/vant/src/tab/README.zh-CN.md
Labels: change: docs

#12933 docs(Tab): fix documentation errors
  packages/vant/src/tab/README.md
  packages/vant/src/tab/README.zh-CN.md
  packages/vant/src/tab/demo/Shrink.vue
  packages/vant/src/tab/demo/index.vue
  packages/vant/src/tab/test/__snapshots__/demo.spec.ts.snap
Labels: change: docs

#12936 docs(Badge): refine the description of 'props'
  packages/vant/src/badge/README.md
  packages/vant/src/badge/README.zh-CN.md
Labels: change: docs

#12937 feat(Form): add prop "scrollToErrorPosition"
  packages/vant/src/form/Form.tsx
  packages/vant/src/form/README.md
  packages/vant/src/form/README.zh-CN.md
Labels: change: feat

#12938 docs(Tab): add FQA for "swipeable" and "animated"
  packages/vant/src/tab/README.md
  packages/vant/src/tab/README.zh-CN.md
Labels: change: docs

#12955 docs(ImagePreview): fix missing parameters
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
Labels: change: docs

#12953 fix(vant-compat): [Toast][Dialog] fix missed and incorrect export error #12952
  packages/vant-compat/src/dialog.ts
  packages/vant-compat/src/toast.ts
Labels: change: fix

#12961 types(Uploader): export afterRead function type
  packages/vant/src/uploader/README.md
  packages/vant/src/uploader/README.zh-CN.md
  packages/vant/src/uploader/index.ts
Labels: change: feat

#12963 docs: fix missing `plain` prop #12962
  packages/vant/src/button/README.md
  packages/vant/src/button/README.zh-CN.md
Labels: change: docs
