Repository youzan/vant, pull requests merged in 2024-01, with the labels that each got.

#12543 docs(changelog): vant v4.8.2
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12547 fix(Tab): tab(with sticky prop) loss 'fixed' classname after switch tab
  packages/vant/src/sticky/Sticky.tsx
  packages/vant/src/tab/test/index.spec.tsx
Labels: change: fix

#12554 docs(Lazyload): fix preLoad type error and spelling mistakes
  packages/vant/src/lazyload/README.md
  packages/vant/src/lazyload/README.zh-CN.md
Labels: change: docs

#12549 fix(Image): ImagePosition type is not exported before
  packages/vant/package.json
  packages/vant/src/image/Image.tsx
  packages/vant/src/image/index.ts
  packages/vant/src/image/types.ts
  packages/vant/tsconfig.json
  pnpm-lock.yaml
Labels: change: fix

#12556 feat(Notify): add teleport prop
  packages/vant/src/notify/Notify.tsx
  packages/vant/src/notify/README.md
  packages/vant/src/notify/README.zh-CN.md
Labels: change: feat

#12560 feat(TextEllipsis): add `action` slot
  packages/vant/src/text-ellipsis/README.md
  packages/vant/src/text-ellipsis/README.zh-CN.md
  packages/vant/src/text-ellipsis/TextEllipsis.tsx
  packages/vant/src/text-ellipsis/demo/index.vue
  packages/vant/src/text-ellipsis/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/text-ellipsis/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/text-ellipsis/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/text-ellipsis/test/index.spec.ts
Labels: change: feat

#12566 feat(ImagePreview): add close-on-click-image prop
  packages/vant/src/image-preview/ImagePreview.tsx
  packages/vant/src/image-preview/ImagePreviewItem.tsx
  packages/vant/src/image-preview/README.md
  packages/vant/src/image-preview/README.zh-CN.md
  packages/vant/src/image-preview/demo/index.vue
  packages/vant/src/image-preview/test/index.spec.ts
  packages/vant/src/image-preview/types.ts
Labels: change: feat

#12577 docs(home): update heading level
  packages/vant/docs/markdown/home.en-US.md
Labels: change: docs

#12576 fix(Tabs): van-border-radius-sm to van-radius-sm
  packages/vant/src/tabs/index.less
Labels: change: fix

#12579 feat(icons): add icon `arrow-double-left` and `arrow-double-right`
  packages/vant-icons/assets/icons.sketch
  packages/vant-icons/src/common.less
  packages/vant-icons/src/config.js
  packages/vant-icons/src/encode-woff2.less
  packages/vant-icons/src/index.less
Labels: change: feat

#12587 feat(Toast): add z-index prop
  packages/vant/src/toast/README.md
  packages/vant/src/toast/README.zh-CN.md
  packages/vant/src/toast/Toast.tsx
  packages/vant/src/toast/types.ts
Labels: change: feat

#12590 docs(changelog): vant@4.8.3
  packages/vant/docs/markdown/changelog.en-US.md
  packages/vant/docs/markdown/changelog.zh-CN.md
Labels: change: docs

#12599 feat(Picker): allow to hidden to toolbar buttons
  packages/vant/src/picker/PickerToolbar.tsx
  packages/vant/src/picker/README.md
  packages/vant/src/picker/README.zh-CN.md
  packages/vant/src/picker/test/index.spec.tsx
Labels: change: feat

#12601 fix(Sticky): initial sticky position
  packages/vant/src/sticky/Sticky.tsx
  packages/vant/src/tab/test/index.spec.tsx
Labels: change: fix
