Repository youzan/vant, pull requests merged in 2024-10, with the labels that each got.

#13147 feat(DatePicker): filter support values param to help get current values
  packages/vant/src/date-picker/DatePicker.tsx
  packages/vant/src/date-picker/README.md
  packages/vant/src/date-picker/README.zh-CN.md
  packages/vant/src/date-picker/utils.ts
  packages/vant/src/time-picker/TimePicker.tsx
Labels: change: feat

#13150 fix(Field): should not adjust value when the min or max props are not set
  packages/vant/src/field/Field.tsx
  packages/vant/src/field/test/index.spec.js
Labels: change: fix

#13127 feat(Calendar): support `text` slot
  packages/vant/src/calendar/Calendar.tsx
  packages/vant/src/calendar/CalendarDay.tsx
  packages/vant/src/calendar/CalendarMonth.tsx
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
  packages/vant/src/calendar/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/calendar/test/index.spec.ts
Labels: change: feat

#13157 docs: fix area data links
  packages/vant/src/area/README.zh-CN.md
Labels: change: docs

#13125 feat(@vant/area-data) upgrade to 2023
  packages/vant-area-data/src/index.ts
Labels: change: fix
