Repository youzan/vant, pull requests merged in 2024-08, with the labels that each got.

#13040 fix(SwipeCell): the click will be triggered after the touchend event on desktop
  packages/vant/src/swipe-cell/SwipeCell.tsx
Labels: change: fix

#13031 docs(Steps): update active-color default value
  packages/vant/src/steps/README.md
  packages/vant/src/steps/README.zh-CN.md
Labels: change: docs

#13061 docs(Calendar): fix inconsistencies between the document and "demo"
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
Labels: change: docs

#13067 fix: use declare module 'vue' instead of @vue/runtime-core
  packages/vant/src/lazyload/vue-lazyload/index.d.ts
Labels: change: fix

#13062 docs(Calendar): improve FQA
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
Labels: change: docs

#13074 fix(vant-area-data): export package.json
  packages/vant-area-data/package.json
Labels: change: fix

#13096 docs(TimePicker): delete useless space
  packages/vant/src/time-picker/demo/index.vue
Labels: change: docs

#13087 feat(Overlay): add teleport prop
  packages/vant/src/overlay/Overlay.tsx
  packages/vant/src/overlay/README.md
  packages/vant/src/overlay/README.zh-CN.md
  packages/vant/src/overlay/test/index.spec.tsx
Labels: change: feat

#13078 docs(Calendar): fix documentation errors
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
  packages/vant/src/calendar/index.less
  packages/vant/src/calendar/types.ts
Labels: change: docs
