Repository youzan/vant, pull requests merged in 2024-09, with the labels that each got.

#13075 fix(Calendar): fix getInitialDate function error
  packages/vant/src/calendar/Calendar.tsx
  packages/vant/src/calendar/test/index.spec.ts
Labels: change: fix

#13077 fix(Calendar): fix watch 'defaultDate' error
  packages/vant/src/calendar/Calendar.tsx
  packages/vant/src/calendar/test/prop.spec.ts
Labels: change: fix

#13068 feat(Field): add min and max props
  packages/vant/src/field/Field.tsx
  packages/vant/src/field/README.md
  packages/vant/src/field/README.zh-CN.md
  packages/vant/src/field/test/index.spec.js
Labels: change: feat

#12972 fix(NumberKeyboard): lose the number 0 key in some configs
  packages/vant/src/number-keyboard/NumberKeyboard.tsx
  packages/vant/src/number-keyboard/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/number-keyboard/test/index.spec.ts
Labels: change: fix

#13120 docs(field): fix field max min property Type
  packages/vant/src/field/README.md
  packages/vant/src/field/README.zh-CN.md
Labels: change: docs

#13122 fix: use data-allow-mismatch to suppress hydration mismatch warnings
  packages/vant/src/address-edit/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/address-edit/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/address-edit/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/back-top/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/back-top/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/cascader/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/cascader/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/cascader/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/config-provider/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/config-provider/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/contact-edit/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/contact-edit/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/coupon-list/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/dropdown-item/DropdownItem.tsx
  packages/vant/src/dropdown-menu/DropdownMenu.tsx
  packages/vant/src/dropdown-menu/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/dropdown-menu/test/__snapshots__/index.spec.tsx.snap
  packages/vant/src/empty/Empty.tsx
  packages/vant/src/empty/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/empty/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/empty/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/field/Field.tsx
  packages/vant/src/field/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/field/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/field/test/__snapshots__/index.spec.js.snap
  packages/vant/src/floating-bubble/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/floating-panel/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/floating-panel/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/form/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/form/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/form/test/__snapshots__/events.spec.tsx.snap
  packages/vant/src/form/test/__snapshots__/props.spec.tsx.snap
  packages/vant/src/icon/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/icon/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/index-bar/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/index-bar/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/list/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/list/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/number-keyboard/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/number-keyboard/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/picker-group/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/picker-group/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/picker/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/picker/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/popover/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/popover/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/pull-refresh/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/pull-refresh/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/search/Search.tsx
  packages/vant/src/search/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/search/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/search/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/tab/Tab.tsx
  packages/vant/src/tab/TabTitle.tsx
  packages/vant/src/tab/test/__snapshots__/demo-ssr.spec.ts.snap
  packages/vant/src/tab/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/tab/test/__snapshots__/index.spec.tsx.snap
  packages/vant/src/tab/test/__snapshots__/insert.spec.tsx.snap
Labels: change: fix

#13136 docs(components): add FAQ for showToast on-demand loading
  packages/vant/src/toast/README.md
  packages/vant/src/toast/README.zh-CN.md
Labels: change: docs
