Repository youzan/vant, pull requests merged in 2025-02, with the labels that each got.

#13334 docs(PickerGroup): add constraints to the end date
  packages/vant/src/picker-group/README.md
  packages/vant/src/picker-group/README.zh-CN.md
Labels: change: docs

#13282 fix(Field): should not modify the value if it's within the min/max
  packages/vant/src/field/Field.tsx
Labels: change: fix

#13350 fix(SwipeCell): unintended stopPropagation when canceling a swipe
  packages/vant/src/swipe-cell/SwipeCell.tsx
  packages/vant/src/swipe-cell/test/index.spec.js
  packages/vant/test/event.ts
Labels: change: fix

#13357 feat(@vant/auto-import-resolver): Support exclude in components or apis
  packages/vant-auto-import-resolver/README.md
  packages/vant-auto-import-resolver/README.zh-CN.md
  packages/vant-auto-import-resolver/src/index.ts
Labels: change: feat

#13363 docs: add a community project named MobVue
  README.md
  README.zh-CN.md
  packages/vant/docs/markdown/home.en-US.md
  packages/vant/docs/markdown/home.zh-CN.md
Labels: change: docs
