Repository youzan/vant, pull requests merged in 2025-01, with the labels that each got.

#13271 fix(CalendarDay): fix margin-bottom calculation wrong for calendar days
  packages/vant/src/calendar/CalendarDay.tsx
  packages/vant/src/calendar/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/calendar/test/__snapshots__/prop.spec.ts.snap
  packages/vant/src/calendar/test/utils.spec.ts
  packages/vant/src/calendar/utils.ts
Labels: change: fix

#13312 feat(Calendar): add click-overlay event
  packages/vant/src/calendar/Calendar.tsx
  packages/vant/src/calendar/README.md
  packages/vant/src/calendar/README.zh-CN.md
  packages/vant/src/calendar/test/index.spec.ts
Labels: change: feat

#13327 feat(Locale): Added polish translations
  packages/vant/src/locale/README.md
  packages/vant/src/locale/lang/pl-PL.ts
Labels: change: feat

#13332 docs(Locale): add Polish to zh documentation
  packages/vant/src/locale/README.md
  packages/vant/src/locale/README.zh-CN.md
Labels: change: docs
