Repository youzan/vant, pull requests merged in 2025-03, with the labels that each got.

#13377 docs: update rolling-text component title
  packages/vant/src/rolling-text/README.zh-CN.md
Labels: change: docs

#13382 feat(Dialog): add destroyOnClose prop to control content destruction on close
  packages/vant/src/dialog/Dialog.tsx
  packages/vant/src/dialog/README.md
  packages/vant/src/dialog/README.zh-CN.md
  packages/vant/src/dialog/function-call.tsx
Labels: change: feat

#13387 docs(Form): fix form basic usage document errors
  packages/vant/src/form/README.md
  packages/vant/src/form/README.zh-CN.md
Labels: change: docs

#13386 fix(Button): fix button active style
  packages/vant/src/button/index.less
Labels: change: fix

#13385 feat(signature): support tips slot
  packages/vant/src/signature/README.md
  packages/vant/src/signature/README.zh-CN.md
  packages/vant/src/signature/Signature.tsx
Labels: change: feat

#13399 docs(Overlay): fix the misleading overlay example
  packages/vant/src/overlay/README.md
  packages/vant/src/overlay/README.zh-CN.md
  packages/vant/src/overlay/demo/index.vue
Labels: change: docs

#13381 fix(Picker): ensure that the confirm event params are up to date
  packages/vant/src/picker/Picker.tsx
  packages/vant/src/picker/test/index.spec.tsx
Labels: change: fix

#13404 types(Dialog): add missing destroyOnClose and keyboardEnabled type
  packages/vant/src/dialog/types.ts
Labels: change: feat
