Repository youzan/vant, pull requests merged in 2025-04, with the labels that each got.

#13422 fix(Watermark): should render KeepAlive with Watermark correctly
  packages/vant/src/watermark/Watermark.tsx
  packages/vant/src/watermark/test/__snapshots__/index.spec.tsx.snap
  packages/vant/src/watermark/test/index.spec.tsx
Labels: change: fix

#13424 fix(Overlay): should inherit attrs when using teleport prop
  packages/vant/src/action-sheet/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/action-sheet/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/calendar/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/calendar/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/coupon-list/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/dropdown-menu/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/dropdown-menu/test/__snapshots__/index.spec.tsx.snap
  packages/vant/src/image-preview/test/__snapshots__/index.spec.ts.snap
  packages/vant/src/overlay/Overlay.tsx
  packages/vant/src/overlay/test/index.spec.tsx
  packages/vant/src/picker/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/popup/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/popup/test/__snapshots__/index.spec.jsx.snap
  packages/vant/src/share-sheet/test/__snapshots__/demo.spec.ts.snap
  packages/vant/src/share-sheet/test/__snapshots__/index.spec.ts.snap
Labels: change: fix

#13426 docs: add press-ui in docs
  README.md
  README.zh-CN.md
  packages/vant/docs/markdown/home.en-US.md
  packages/vant/docs/markdown/home.zh-CN.md
Labels: change: docs

#13429 feat(FloatingBubble): allow gap xy to be set separately (#13297)
  packages/vant/src/floating-bubble/FloatingBubble.tsx
  packages/vant/src/floating-bubble/README.md
  packages/vant/src/floating-bubble/README.zh-CN.md
  packages/vant/src/floating-bubble/test/index.spec.ts
  packages/vant/src/floating-bubble/types.ts
Labels: change: feat

#13443 feat(Popup): add overlay-props prop
  packages/vant/src/dropdown-item/DropdownItem.tsx
  packages/vant/src/popup/Popup.tsx
  packages/vant/src/popup/README.md
  packages/vant/src/popup/README.zh-CN.md
  packages/vant/src/popup/shared.ts
Labels: change: feat

#13425 fix(Picker): makesure confirm params' behavior consistent (#13423)
  packages/vant/src/picker/Picker.tsx
  packages/vant/src/picker/test/index.spec.tsx
Labels: change: fix

#13445 fix(Picker): update selected values when modelValue is cleared
  packages/vant/src/picker/Picker.tsx
  packages/vant/src/picker/test/index.spec.tsx
Labels: change: fix

#13456 docs: correct window.innerWidth to window.innerHeight in FloatingPanel
  packages/vant/src/floating-panel/README.md
  packages/vant/src/floating-panel/README.zh-CN.md
Labels: change: docs
