Repository youzan/vant, pull requests merged in 2025-06, with the labels that each got.

#13506 docs(Field): add field version number for A's props
  packages/vant/src/field/README.md
  packages/vant/src/field/README.zh-CN.md
Labels: change: docs

#13498 docs(Uploader): optimize parameter description
  packages/vant/src/uploader/README.md
  packages/vant/src/uploader/README.zh-CN.md
Labels: change: docs

#13487 feat(image): add native `decoding` prop to Image component
  packages/vant/src/image/Image.tsx
Labels: change: feat

#13519 fix(Progress): width overflow
  packages/vant/src/progress/Progress.tsx
  packages/vant/src/progress/demo/index.vue
Labels: change: fix
